### ISSUE TITLE
Enable enableTime by props dynamically

### ISSUE THREAD

**Issue by wiesson** [coderhaoxin/react-flatpickr#31]
Is it possible to switch between the `enableTime` option? (e.g. via Checkbox?)

**Comment by wiesson** [comment]
Yes, but unfortunately it didn't work..

**Comment by jacobmischka** [comment]
You can trick react into recreating the flatpickr component by using a key like this:

```jsx
<input type='checkbox' checked={this.state.enableTime} value='enableTime'
     onChange={() => { this.setState({enableTime: !this.state.enableTime}) }} />
<Flatpickr
     key={`enable-time-${this.state.enableTime ? 'true' : 'false'}`}
     options={{
         enableTime: this.state.enableTime
     }} />
```

Should work!

**Comment by jacobmischka** [comment]
Closing because I believe it's out of scope for this project, but please feel free to comment if that's still not working.

Unfortunately, this is something that's sort of out of our control, as we're essentially just passing props to flatpickr, which does all the heavy lifting. Might be worthwhile raising an issue there if the example workaround above doesn't work for you.

**Comment by ndinhphi** [comment]
@jacobmischka I missing 'key' so it not working. Thank you for your help!
