### ISSUE TITLE
How to localize?

### ISSUE THREAD

**Issue by chroz** [coderhaoxin/react-flatpickr#39]
import 'flatpickr/dist/l10n/no.js';

  <Flatpickr options={{ locale: 'no'}}/>

index_bundle.js:35038 flatpickr: invalid locale no

**Comment by jacobmischka** [comment]
Please use the module loading method described in [flatpickr docs](https://chmln.github.io/flatpickr/localization/#using-modules). Please see [this comment](https://github.com/coderhaoxin/react-flatpickr/issues/16#issuecomment-293780090) in issue #16 for a few more details. If you run into problems feel free to write back, but I'm closing this for now because that should solve your issue.
