### ISSUE TITLE
Today button

### ISSUE THREAD

**Issue by vfonic** [coderhaoxin/react-flatpickr#42]
What would be the easiest way to achieve "Today" button on/or outside of the component:
https://github.com/chmln/flatpickr/issues/202#issuecomment-235801957

Thank you!

**Comment by vfonic** [comment]
Nevermind, I checked the source code and figured that `defaultDate` option is not part of options prop, but is a separate prop. Not sure why though.

Not working:
```jsx
<Flatpickr
        options={{
          defaultDate: value,
          enable: dates
        }}
      />
```

Working:
```jsx
<Flatpickr
        defaultDate={value}
        options={{
          enable: dates
        }}
      />
```

**Comment by jacobmischka** [comment]
Hm, `defaultValue` is a prop instead of part of the object because it's assigned to the DOM element. And all of the [hooks](https://chmln.github.io/flatpickr/events/) are props so we can do a little checking on them (because they need to be arrays when dynamically updating them to flatpickr).

I don't believe `defaultDate` is a prop that we're paying any attention to in this library, so that's weird, but I'm glad you got it working.

**Comment by MrBrax** [comment]
I really like the look of this picker, but not having a today/"right now" button feels like a dealbreaker, i'll have to add buttons next to the text fields instead.
It's so ridiculously hard to find libraries that don't depend on jQuery today.
