### ISSUE TITLE
Remove minDate, maxDate and dateFormat from props

### ISSUE THREAD

**Issue by ZeHiro** [coderhaoxin/react-flatpickr#47]
Hi,

Thanks for this library. 

When using minDate and maxDate and dateFromat through the props, instead of the option object, the options object is passed correctly to flatpickr, but React (16) throws a warning saying it will not pass it to the input, which is "normal" as the input is a text input, and these attributes do not exist for a text input.

Passing the minDate/maxDate etc as props is interesting to limit rerenders (the options objetc has to be recreated each rerender of the parent component of 'react-flatplickr'), which retrigers a rerender.

The maxDate, minDate and other options for flatpickr shall be added to the 'hooks' array (here https://github.com/coderhaoxin/react-flatpickr/blob/master/lib/index.js#L6) so that they are also removed from the props passed to the input (here: https://github.com/coderhaoxin/react-flatpickr/blob/master/lib/index.js#L102)

I can make a PR if necessary.

**Comment by jacobmischka** [comment]
I don't believe `minDate`, `maxDate`, or `dateFormat` are supported props for this component. The only supported props are the ones listed in `propTypes`, which are the hooks, `value`, `defaultValue`, and `children`.

We don't currently pass any non-hook options to flatpickr, at least not intentionally.

Please let me know where we're currently doing that if we are, it's not intended.

**Comment by ZeHiro** [comment]
I think I didn't explain myself. I would like to use the component like this : 
```jsx
<FlatPicker
   minDate={'aDate'}
   maxDate={'anotherDate'}
   dateFormat='d/m/y'
/>
```
This is not possible right now, an we have to use the `options` objects to pass them down.

But if `maxDate`, `minDate` etc were added to the `hooks` array, they would be automatically transfered to the flatpicker object, and not passed as props to the input.

**Comment by jacobmischka** [comment]
Ah. Sorry, currently the intended way to do this is to pass it via the options object as you realized.

Those options aren't hooks, they're just configuration options. Hooks are an outlier, currently we keep track of all hooks because we need to ensure they're passed to flatpickr as an array. Since we're keeping track of them anyway, allowing them to be specified as props isn't much extra work. But I don't want to add to that and couple this package even more with changes to flatpickr options.

Sorry!
