### ISSUE TITLE
How do I enable start & end time for the date range picker?

### ISSUE THREAD

**Issue by CodeBradley** [coderhaoxin/react-flatpickr#75]
I've set the option to enable the date range picker, but when I set data-enable-time it only allows me to select one time, rather than a start and an end time. I would like users to submit a start and an end time. How would I enable this?

```javascript
import React from "react";
import ReactDOM from "react-dom";
import Flatpickr from "react-flatpickr";
import "./styles.css";

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      date: new Date()
    };
  }

  render() {
    const { date } = this.state;
    return (
      <div className="App">
        <h1>Flatpickr Test</h1>
        <Flatpickr
          data-enable-time
          value={[date, "2016-01-10"]}
          options={{ mode: "range" }}
          onChange={(_, str) => console.info(str)}
        />
      </div>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

Working code:
https://codesandbox.io/s/14r8y26163

**Comment by jacobmischka** [comment]
It is enabled, it's just not particularly intuitive. After selecting each date you can change the time:

![peek 2018-11-26 04-52](https://user-images.githubusercontent.com/3939997/49009831-27524b00-f137-11e8-92ce-61d0a9882169.gif)

This is all handled by flatpickr itself, not this package, so sorry, there's not a whole lot we can do about it here. In practice, I often end up using two individual inputs instead of one for ranges, though it is more of a pain.
